name:                recursion-schemes-by-example
version:             0.1.0.0
github:              "ChrisPenner/-examplesample"
license:             BSD3
author:              "Chris Penner"
maintainer:          "christopher.penner@gmail.com"
copyright:           "Chris Penner"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Other

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ChrisPenner/recursion-schemes-by-example#readme>

library:
  source-dirs: src
  ghc-options:
  - -Wall

dependencies:
- base >= 4.7 && < 5
- recursion-schemes
- mtl
- free
- aeson
- containers
- unordered-containers
- deriving-compat
- vector
- text
- bytestring
- doctest
- comonad

tests:
  recursion-schemes-by-example-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - recursion-schemes-by-example
